---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-api
  namespace: bank
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: bank
      component: api
      container: api
  replicas: 2
  template:
    metadata:
      labels:
        app: bank
        component: api
        container: api
    spec:
      containers:
        - name: api
          image: gcr.io/tf-ops-cicd-97aadd/bank/api/main/api:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env: 
            - name: PORT
              value: "8080"
            - name: PROJECT_ID
              value: "tf-bank-api-dev-dd4999"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secrets/google/key.json"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: app-level-config
            - configMapRef:
                name: env-level-config
            - configMapRef:
                name: component-level-config-api
            - configMapRef:
                name: container-level-config-api-api
          volumeMounts:
            - mountPath: "/etc/secrets/google"
              name: google
              readOnly: true
      volumes:
        - name: google
          secret:
            secretName: api-api-google
      imagePullSecrets:
        - name: image-pull-secret
