---
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-level-config-portal
  namespace: e2e
data:
  COMPONENT_ID: portal
  COMPONENT_NAME: portal
  COMPONENT_DOMAIN_NAME: american-broomstick.com
