---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-static
  namespace: e2e
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: e2e
      component: portal
      container: static
  replicas: 1
  template:
    metadata:
      labels:
        app: e2e
        component: portal
        container: static
    spec:
      containers:
        - name: static
          image: gcr.io/tf-ops-cicd-97aadd/e2e/portal/main/static:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: app-level-config
            - configMapRef:
                name: env-level-config
            - configMapRef:
                name: component-level-config-portal
            - configMapRef:
                name: container-level-config-portal-static
          volumeMounts:
            - mountPath: "/etc/secrets/pull-key"
              name: pull-key
              readOnly: true
      volumes:
        - name: pull-key
          secret:
            secretName: pull-key
      imagePullSecrets:
        - name: image-pull-secret
