---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-api
  namespace: eg
spec:
  template:
    spec:
      containers:
        - name: api
          image: gcr.io/tf-ops-cicd-97aadd/eg/website/dev/api:425826e
