---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-static
  namespace: eg
spec:
  template:
    spec:
      containers:
        - name: static
          image: gcr.io/tf-ops-cicd-97aadd/eg/website/dev/static:latest
