---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Address Australia.
  sourceRepos:
    - '*'
  destinations:
    - namespace: aa
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
