---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-api
  namespace: aa
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: aa
      component: api
      container: api
  replicas: 1
  template:
    metadata:
      labels:
        app: aa
        component: api
        container: api
    spec:
      containers:
        - name: api
          image: gcr.io/tf-ops-cicd-97aadd/aa/api/main/api:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env: 
            - name: PORT
              value: "8080"
            - name: FIRESTORE_PROJECT_ID
              value: "tf-aa-website-dev-338608"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secrets/google/key.json"
            - name: SOLR_PORT
              value: "8985"
            - name: SOLR_PROTOCOL
              value: "http"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-api-token
                  key: token
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: app-level-config
            - configMapRef:
                name: env-level-config
            - configMapRef:
                name: component-level-config-api
            - configMapRef:
                name: container-level-config-api-api
          volumeMounts:
            - mountPath: "/etc/secrets/google"
              name: google
              readOnly: true
            - mountPath: "/etc/secrets/token"
              name: token
              readOnly: true
      volumes:
        - name: google
          secret:
            secretName: api-api-google
        - name: token
          secret:
            secretName: api-api-token
      imagePullSecrets:
        - name: image-pull-secret
