---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-api
  namespace: tw
spec:
  template:
    spec:
      containers:
        - name: api
          image: gcr.io/tf-ops-cicd-97aadd/tw/website/dev/api:latest
