---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-static
  namespace: tw
spec:
  template:
    spec:
      containers:
        - name: static
          image: gcr.io/tf-ops-cicd-97aadd/tw/website/dev/static:714e978
