---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-components
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
      repoURL: https://github.com/francisco-com-au/platform-apps.git
      revision: main
      directories:
        - path: 'managed/lab/components/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: lab
      source:
        repoURL: https://github.com/francisco-com-au/platform-apps.git
        targetRevision: main
        path: '{{path}}/overlays/prod'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
