---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: lab
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    description: A free product to test and break things manually.
    sourceRepos:
    - '*'
    destinations:
    - namespace: lab
    server: https://kubernetes.default.svc
    - namespace: '*'
    server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
    kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
    kind: '*'
    