---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website
  namespace: aa
spec:
  dnsNames:
    - website.addressaustralia.com.au
  secretName: website-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
