apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easy-gifts-website
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: easy-gifts
  source:
    repoURL: git@github.com:galarzafrancisco/easy.gifts-env.git
    targetRevision: HEAD
    path: website
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: easy-gifts
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true