---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-static
  namespace: aa
spec:
  template:
    spec:
      containers:
        - name: static
          image: gcr.io/tf-ops-cicd-97aadd/aa/website/dev/static:21ab478
