---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-api
  namespace: aa
spec:
  template:
    spec:
      containers:
        - name: api
          image: gcr.io/tf-ops-cicd-97aadd/aa/website/dev/api:b1bc239
