---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
# apiVersion: apps/v1
# kind: Deployment
metadata:
  name: website-mongo
  namespace: aa
spec:
  template:
    spec:
      containers:
        - name: mongo
          image: mongo:3.6.23
