---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: e2e-components
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/francisco-com-au/platform-apps.git
        revision: main
        directories:
          - path: 'managed/apps/e2e/components/*'
  template:
    metadata:
      name: 'e2e-{{path.basename}}'
    spec:
      project: e2e
      source:
        repoURL: https://github.com/francisco-com-au/platform-apps.git
        targetRevision: main
        path: '{{path}}/overlays/prod'
      destination:
        server: https://kubernetes.default.svc
        namespace: e2e
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
