---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: e2e
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: End to end testing, from definition to container built
  sourceRepos:
    - '*'
  destinations:
    - namespace: e2e
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
