---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: e2e-components
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/francisco-com-au/platform-apps.git
        revision: main
        directories:
          - path: 'managed/e2e/components/*'
  template:
    spec:
      source:
        targetRevision: main
        path: '{{path}}/overlays/dev'
