apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: dev
spec:
  dnsNames:
    - grafana.francisco.com.au
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer