apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex
  namespace: home-ingress
spec:
  dnsNames:
    - plex.francisco.com.au
  secretName: plex-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer