---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - component-level-config-website.yaml
  - container-level-config-website-mongo.yaml
  - deploy-website-mongo.yaml
  - svc-website-mongo-mongo.yaml
  - container-level-config-website-static.yaml
  - deploy-website-static.yaml
  - svc-website-static-webserver.yaml
  - container-level-config-website-api.yaml
  - deploy-website-api.yaml
  - svc-website-api-api.yaml
  - secret-google.yaml
  - secret-website-sessions-mongo.yaml
  - secret-sendgrid-key.yaml
  - secret-stripe-key.yaml
  - secret-main-key.yaml
  - cert-website.yaml
  - ingress-website.yaml



