---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-static
  namespace: e2e
spec:
  template:
    spec:
      containers:
        - name: static
          image: gcr.io/tf-ops-cicd-97aadd/e2e/portal/dev/static:87a0483
