---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-nginx
  namespace: lab
spec:
  selector:
    matchLabels:
      app: lab
      component: playground
      container: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: lab
        component: playground
        container: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports: 
            - containerPort: 80
          
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
