---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Gift recommender
  sourceRepos:
    - '*'
  destinations:
    - namespace: eg
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
