---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-static
  namespace: ai
spec:
  template:
    spec:
      containers:
        - name: static
          image: gcr.io/tf-ops-cicd-97aadd/ai/website/dev/static:c769c77
