---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: website
  namespace: ai
spec:
  tls:
  - hosts:
    - dev.ai.home.galarza.business
    secretName: website-tls
  rules:
  - host: dev.ai.home.galarza.business
    http:
      paths: 
        - path: /
          pathType: Prefix
          backend:
            service:
              name: website-static-webserver
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: website-api-api
              port:
                number: 8080
