---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-api
  namespace: bank
spec:
  template:
    spec:
      containers:
        - name: api
          image: gcr.io/tf-ops-cicd-97aadd/bank/api/dev/api:latest
