---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website
  namespace: bank
spec:
  dnsNames:
    - bank.american-broomstick.com
  secretName: website-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
