apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: assistant
  namespace: dev
spec:
  dnsNames:
    - assistant.francisco.com.au
  secretName: assistant-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer