---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - component-level-config-website.yaml
  - container-level-config-website-static.yaml
  - deploy-website-static.yaml
  - svc-website-static-nginx.yaml
  - container-level-config-website-api.yaml
  - deploy-website-api.yaml
  - svc-website-api-nginx.yaml
  - secret-website-api-google.yaml
  - cert-website.yaml
  - ingress-website.yaml



