---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bank-components
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/francisco-com-au/platform-apps.git
        revision: develop
        directories:
          - path: 'managed/apps/bank/components/*'
  template:
    spec:
      source:
        targetRevision: develop
        path: '{{path}}/overlays/dev'
