apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: address-australia-api-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: address-australia
  source:
    repoURL: git@github.com:address-australia/env.git
    targetRevision: HEAD
    path: api
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
