---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patches/cert-discovery.yaml
  - patches/ingress-discovery.yaml
  - patches/deploy-discovery-static.yaml
  - patches/deploy-discovery-api.yaml

