---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-api
  namespace: tw
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: tw
      component: api
      container: api
  replicas: 1
  template:
    metadata:
      labels:
        app: tw
        component: api
        container: api
    spec:
      containers:
        - name: api
          image: gcr.io/tf-ops-cicd-97aadd/tw/api/main/api:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env: 
            - name: PORT
              value: "8080"
            - name: MONGO_HOST
              value: "api-database-mongo"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              value: "twister"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: app-level-config
            - configMapRef:
                name: env-level-config
            - configMapRef:
                name: component-level-config-api
            - configMapRef:
                name: container-level-config-api-api
          volumeMounts:
      volumes:
      imagePullSecrets:
        - name: image-pull-secret
