---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api
  namespace: tw
  # annotations:
  #  nginx.ingress.kubernetes.io/backend-protocol: https # ingress-nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - api.twister.american-broomstick.com
      secretName: api-tls
  rules:
    - host: api.twister.american-broomstick.com
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-api-api
                port:
                  number: 8080
