---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patches/cert-api.yaml
  - patches/ingress-api.yaml
  - patches/deploy-api-api.yaml

